/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */

import { Signer, utils, Contract, ContractFactory, Overrides } from "ethers";
import { Provider, TransactionRequest } from "@ethersproject/providers";
import type {
  BalanceContract,
  BalanceContractInterface,
} from "../BalanceContract";

const _abi = [
  {
    inputs: [],
    stateMutability: "nonpayable",
    type: "constructor",
  },
  {
    inputs: [],
    name: "getOwnerBalance",
    outputs: [
      {
        internalType: "uint256",
        name: "",
        type: "uint256",
      },
    ],
    stateMutability: "view",
    type: "function",
  },
  {
    inputs: [],
    name: "owner",
    outputs: [
      {
        internalType: "address",
        name: "",
        type: "address",
      },
    ],
    stateMutability: "view",
    type: "function",
  },
  {
    stateMutability: "payable",
    type: "receive",
  },
];

const _bytecode =
  "0x608060405234801561001057600080fd5b50336000806101000a81548173ffffffffffffffffffffffffffffffffffffffff021916908373ffffffffffffffffffffffffffffffffffffffff1602179055506102ea806100606000396000f3fe60806040526004361061002d5760003560e01c8063590791f2146100395780638da5cb5b1461006457610034565b3661003457005b600080fd5b34801561004557600080fd5b5061004e61008f565b60405161005b91906101fd565b60405180910390f35b34801561007057600080fd5b5061007961015d565b60405161008691906101c2565b60405180910390f35b60008060009054906101000a900473ffffffffffffffffffffffffffffffffffffffff1673ffffffffffffffffffffffffffffffffffffffff163373ffffffffffffffffffffffffffffffffffffffff1614610120576040517f08c379a0000000000000000000000000000000000000000000000000000000008152600401610117906101dd565b60405180910390fd5b60008054906101000a900473ffffffffffffffffffffffffffffffffffffffff1673ffffffffffffffffffffffffffffffffffffffff1631905090565b60008054906101000a900473ffffffffffffffffffffffffffffffffffffffff1681565b61018a81610229565b82525050565b600061019d602683610218565b91506101a882610265565b604082019050919050565b6101bc8161025b565b82525050565b60006020820190506101d76000830184610181565b92915050565b600060208201905081810360008301526101f681610190565b9050919050565b600060208201905061021260008301846101b3565b92915050565b600082825260208201905092915050565b60006102348261023b565b9050919050565b600073ffffffffffffffffffffffffffffffffffffffff82169050919050565b6000819050919050565b7f536f6c6f20656c206475656e6f20707565646520636f6e73756c74617220737560008201527f2073616c646f000000000000000000000000000000000000000000000000000060208201525056fea264697066735822122012a8f092cecbd9d3ff85081fb8343106c0353b81829fdef635755c227f4fb19a64736f6c63430008040033";

export class BalanceContract__factory extends ContractFactory {
  constructor(
    ...args: [signer: Signer] | ConstructorParameters<typeof ContractFactory>
  ) {
    if (args.length === 1) {
      super(_abi, _bytecode, args[0]);
    } else {
      super(...args);
    }
  }

  deploy(
    overrides?: Overrides & { from?: string | Promise<string> }
  ): Promise<BalanceContract> {
    return super.deploy(overrides || {}) as Promise<BalanceContract>;
  }
  getDeployTransaction(
    overrides?: Overrides & { from?: string | Promise<string> }
  ): TransactionRequest {
    return super.getDeployTransaction(overrides || {});
  }
  attach(address: string): BalanceContract {
    return super.attach(address) as BalanceContract;
  }
  connect(signer: Signer): BalanceContract__factory {
    return super.connect(signer) as BalanceContract__factory;
  }
  static readonly bytecode = _bytecode;
  static readonly abi = _abi;
  static createInterface(): BalanceContractInterface {
    return new utils.Interface(_abi) as BalanceContractInterface;
  }
  static connect(
    address: string,
    signerOrProvider: Signer | Provider
  ): BalanceContract {
    return new Contract(address, _abi, signerOrProvider) as BalanceContract;
  }
}
